package org.example.enums;

public enum UserState {
    BASIC_STATE,
    WAITING_FOR_NAME,
    WAITING_FOR_YEAR,
    WAITING_FOR_MONTH,
    WAITING_FOR_DAY,
    WAITING_FOR_REMIND,
    WAITING_FOR_REMIND_TIME,
    DELETE_TASKS_STATE,
    EDIT_PHOTO_STATE,
    EDIT_REMIND_STATE,
    WAITING_FOR_CHANGE_REMIND
}